name: Unity CI

on:
  push:
    branches: [ main, dev ]  # Запуск при пуше в эти ветки
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4
        with:
          lfs: true  # Для Unity-ассетов

      # Шаг 2: Установка лицензии Unity
      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: path/to/your/project
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      
      # Шаг 3: Сборка проекта
      - name: Build Unity Project (WebGL)
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
          projectPath: .

      # Шаг 4: Запуск тестов (если есть)
      - name: Run Unit Tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: .
